import 'district.dart';
import 'is_like.dart';

class ListingDetail {
  String id;
  String title;
  String status;
  String description;
  String ownerName;
  String provinceCode;
  String districtCode;
  String wardCode;
  String streetName;
  String fullAddress;
  dynamic latitude;
  dynamic longitude;
  String commissionRatePercent;
  dynamic commissionAmountVnd;
  String legalAreaSqm;
  String actualAreaSqm;
  String frontageMeters;
  String widthMeters;
  dynamic roadWidthMeters;
  int numberOfFloors;
  String listingPriceVndSell;
  String? listingPriceVndRent; // có thể null
  String createdBy;
  String updatedBy;
  DateTime createdAt;
  DateTime updatedAt;
  String authorName;
  String phoneNumber;
  List<String> imageUrls;
  List<String> tags;
  String propertyType; // thay cho realEstateType
  District province;
  District district;
  District ward;
  int likes;
  String ownerPhoneNumber;
  String ownerCitizenId;
  int numberOfRooms;
  int numberOfBathrooms;
  int numberOfBalconies;
  dynamic facing;
  dynamic landCertificate;
  String listingCode;
  String listingType;
  IsLiked isLiked;

  ListingDetail({
    required this.id,
    required this.title,
    required this.status,
    required this.description,
    required this.ownerName,
    required this.provinceCode,
    required this.districtCode,
    required this.wardCode,
    required this.streetName,
    required this.fullAddress,
    required this.latitude,
    required this.longitude,
    required this.commissionRatePercent,
    required this.commissionAmountVnd,
    required this.legalAreaSqm,
    required this.actualAreaSqm,
    required this.frontageMeters,
    required this.widthMeters,
    required this.roadWidthMeters,
    required this.numberOfFloors,
    required this.listingPriceVndSell,
    required this.listingPriceVndRent,
    required this.createdBy,
    required this.updatedBy,
    required this.createdAt,
    required this.updatedAt,
    required this.authorName,
    required this.phoneNumber,
    required this.imageUrls,
    required this.tags,
    required this.propertyType,
    required this.province,
    required this.district,
    required this.ward,
    required this.likes,
    required this.ownerPhoneNumber,
    required this.ownerCitizenId,
    required this.numberOfRooms,
    required this.numberOfBathrooms,
    required this.numberOfBalconies,
    required this.facing,
    required this.landCertificate,
    required this.listingCode,
    required this.listingType,
    required this.isLiked,
  });
}
