platform :ios, '14.0'
pod 'GoogleMaps', '~> 7.0'

target 'Runner' do
  use_frameworks!       # Bắt buộc cho Swift module như GoogleMaps
  use_modular_headers!   # Giúp pods Swift/ObjC tương thích
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end