platform :ios, '14.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  # Google Maps plugin
  pod 'GoogleMaps', '~> 7.0'

  # flutter_image_compress plugin
  pod 'flutter_image_compress', :path => '../.symlinks/plugins/flutter_image_compress/ios'
  pod 'flutter_image_compress_common', :path => '../.symlinks/plugins/flutter_image_compress/ios'

  # Thêm các plugin khác tương tự, ví dụ:
  # pod 'firebase_core', :path => '../.symlinks/plugins/firebase_core/ios'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Swift 5
      config.build_settings['SWIFT_VERSION'] = '5.0'
      # Fix M1/M2 simulator
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
